# Ground Station

telemetry_handler:
  ros__parameters:
      visualization:
        known_base_radius: 1.5


telemetry_recorder:
  ros__parameters:
    recording:
      enable: false
      max_duration_minutes: 10
      max_file_size_mb: 1000
      include_images: false
      recording_formats: ["rosbag"]
      output_directory: "~/frtl_2025_ws/flight_logs/ground_station"
      autosave_time: 180.0  # Auto-save every 3 minutes

telemetry_dashboard:
  ros__parameters:
    network:
      ping_target: "8.8.8.8"  # Network monitoring target
      ground_station_ip: "192.168.0.100"
    topics:
      position: "/telemetry/position"
      drone_status: "/telemetry/drone_status"
      system_health: "/telemetry/system_health" 
      logs: "/telemetry/logs"