fase4_fsm:
  ros__parameters:
    # Home position parameter
    fictual_home_x: 0.0
    fictual_home_y: 0.0
    fictual_home_z: 0.0 # Remember z points Down

    # Takeoff parameters
    takeoff_height: -1.5
    max_vertical_velocity: 0.5
    
    # Lane following parameters
    max_horizontal_velocity: 0.5
    max_yaw_rate: 1.0
    position_tolerance: 0.1

    # PID parameters for positioning
    pid_pos_kp: 1.0
    pid_pos_ki: 0.0
    pid_pos_kd: 0.0
    setpoint: 0.0

    # Lane following PID - Controle lateral (alinhamento em X)
    pid_lateral_kp: 1.0
    pid_lateral_ki: 0.0
    pid_lateral_kd: 0.0 

    # Lane following PID - Controle angular (alinhamento em theta)
    pid_angular_kp: 1.0
    pid_angular_ki: 0.01
    pid_angular_kd: 0.1

fase4_vision:
  ros__parameters:
    timeout: 10.0