fase4_fsm:
  ros__parameters:
    # Home position parameter
    fictual_home_x: 0.0
    fictual_home_y: 0.0
    fictual_home_z: 0.0 # Remember z points Down

    # Takeoff parameters
    takeoff_height: -1.5
    max_vertical_velocity: 0.5

    # Meia Volta Volver parameters
    yaw_tolerance: 0.087 # 5 graus em rad
    volver_timeout: 15.0

    # Landing parameters
    landing_velocity: 0.3
    landing_timeout: 10.0
    
    # Lane following parameters
    max_horizontal_velocity: 0.5
    max_yaw_rate: 1.0
    position_tolerance: 0.1
    max_angle_for_translation: 0.523 # 30 degrees in radians

    # PID parameters for positioning (valores mais conservadores)
    pid_pos_kp: 0.8
    pid_pos_ki: 0.0  
    pid_pos_kd: 0.4
    setpoint: 0.0

    # Lane following PID - Controle lateral (alinhamento em X)
    pid_lateral_kp: 1.2
    pid_lateral_ki: 0.0
    pid_lateral_kd: 1.0

    # Lane following PID - Controle angular (alinhamento em theta)
    pid_angular_kp: 0.8
    pid_angular_ki: 0.0
    pid_angular_kd: 1.6

fase4_vision:
  ros__parameters:
    timeout: 10.0