fase4_fsm:
  ros__parameters:
    # Home position parameter
    fictual_home_x: 0.0
    fictual_home_y: 0.0
    fictual_home_z: 0.0 # Remember z points Down

    # Takeoff parameters
    takeoff_height: -1.5
    max_vertical_velocity: 0.5
    initial_takeoff_taken: false

    # Circle detection parameters
    has_ever_detected_circle: false
    last_x_circle: 0.0
    last_y_circle: 0.0
    timeout_circle_detection: 10.0 # Timeout for circle detection
    normalized_position_tolerance_circle_align: 0.05

    # Meia Volta Volver parameters
    yaw_tolerance: 0.087 # 5 graus em rad
    volver_timeout: 15.0

    # Landing parameters
    landing_velocity: 0.3
    landing_timeout: 10.0
    has_ever_landed: false

    # garra
    command_to_drop_script: "echo ESTOU SOLTANDO A GARRA!!" #"python3 /home/evtol/frtl_2025_ws/src/scripts/gancho_drop.py open"

    # Lane following parameters
    max_horizontal_velocity: 0.5
    max_yaw_rate: 1.0
    position_tolerance: 0.1
    max_angle_for_translation: 0.523 # 30 degrees in radians
    angulo_muito_pequeno_seguir_reto: 0.34 # 20 degrees in radians (muito grande em relacao à vertical, mas faz 20 com a horizontal)

    # PID parameters for positioning (valores mais conservadores)
    pid_pos_kp: 2.0
    pid_pos_ki: 0.0
    pid_pos_kd: 0.5
    setpoint: 0.0

    # Lane following PID - Controle lateral (alinhamento em x)
    pid_lateral_kp: 1.0
    pid_lateral_ki: 0.0
    pid_lateral_kd: 0.3

    # Lane following PID - Controle angular (alinhamento em theta)
    pid_angular_kp: 1.0
    pid_angular_ki: 0.0
    pid_angular_kd: 0.7

fase4_vision:
  ros__parameters:
    timeout: 10.0