fase4_fsm:
  ros__parameters:
    # Home position parameter
    fictual_home_x: 0.0
    fictual_home_y: 0.0
    fictual_home_z: 0.0 # Remember z points Down

    fig_count: 0
    max_number_of_bases: 6

    position_tolerance: 0.1
    timeout_duration: 10.0

    # Takeoff parameters
    takeoff_height: -1.5
    max_vertical_velocity: 0.5
    initial_takeoff_taken: false

    # Landing parameters
    landing_velocity: 0.3
    landing_timeout: 10.0

    # PID parameters for positioning (valores mais conservadores)
    pid_pos_kp: 2.0
    pid_pos_ki: 0.0
    pid_pos_kd: 0.5
    setpoint: 0.0

    # Pontos_waypoints
    wp_A_x: -4.0
    wp_A_y: 0.0

    wp_B_x: -4.0
    wp_B_y: 4.0

    wp_C_x: 0.0
    wp_C_y: 4.0

fase4_vision:
  ros__parameters:
    timeout: 10.0