# Onboard computer

oak_rgb_publisher:
  ros__parameters:
    publish_raw: true
    publish_compressed: false
    width: 800
    height: 800
    fps: 10
    auto_exposure_compensation: 1

fase3_color_detector:
  ros__parameters:
    image_topic: '/vertical_camera'
    area_minima_bases: 2000  # Increased to reduce false positives
    
    # Debug mode parameters - similar to CBR base_detector
    full_debug_mode: false  # Publishes full-quality annotated images for debugging
    light_debug_mode: true  # Publishes compressed images at 3Hz for telemetry
    light_debug_topic: '/telemetry/camera_debug/compressed'
    light_debug_size: 400  # Resize debug images to 400x400 for bandwidth
    light_debug_quality: 75  # JPEG compression quality (75% for good quality/size balance)
    
    circulo:
      hue_lower: 117  # Calibrated from circulo.txt
      hue_upper: 132  # Calibrated from circulo.txt
      saturation_lower: 100  # Calibrated from circulo.txt
      saturation_upper: 189  # Calibrated from circulo.txt
      value_lower: 234  # Calibrated from circulo.txt
      value_upper: 255  # Calibrated from circulo.txt

    triangulo:
      hue_lower: 108  # Calibrated from triangulo.txt
      hue_upper: 123  # Calibrated from triangulo.txt
      saturation_lower: 105  # Calibrated from triangulo.txt
      saturation_upper: 225  # Calibrated from triangulo.txt
      value_lower: 91  # Calibrated from triangulo.txt
      value_upper: 255  # Calibrated from triangulo.txt

    hexagono:
      hue_lower: 0  # Calibrated from hexagono.txt
      hue_upper: 179  # Calibrated from hexagono.txt
      saturation_lower: 120  # Calibrated from hexagono.txt
      saturation_upper: 167  # Calibrated from hexagono.txt
      value_lower: 239  # Calibrated from hexagono.txt
      value_upper: 255  # Calibrated from hexagono.txt

    hexagono2: # Para wrap-around do vermelho - DISABLED
      hue_lower: 0
      hue_upper: 0
      saturation_lower: 0
      saturation_upper: 0
      value_lower: 0
      value_upper: 0

    pentagono:
      hue_lower: 150  # Calibrated from pentagono.txt
      hue_upper: 190  # Calibrated from pentagono.txt
      saturation_lower: 90  # Calibrated from pentagono.txt
      saturation_upper: 190  # Calibrated from pentagono.txt
      value_lower: 139  # Calibrated from pentagono.txt
      value_upper: 200  # Calibrated from pentagono.txt

    estrela:
      hue_lower: 43  # Calibrated from estrela.txt
      hue_upper: 62  # Calibrated from estrela.txt
      saturation_lower: 22  # Calibrated from estrela.txt
      saturation_upper: 231  # Calibrated from estrela.txt
      value_lower: 121  # Calibrated from estrela.txt
      value_upper: 183  # Calibrated from estrela.txt

    cruz:
      hue_lower: 145  # Calibrated from cruz.txt
      hue_upper: 160  # Calibrated from cruz.txt
      saturation_lower: 82  # Calibrated from cruz.txt
      saturation_upper: 182  # Calibrated from cruz.txt
      value_lower: 158  # Calibrated from cruz.txt
      value_upper: 218  # Calibrated from cruz.txt

    casa:
      hue_lower: 3  # Calibrated from casa.txt
      hue_upper: 18  # Calibrated from casa.txt
      saturation_lower: 35  # Calibrated from casa.txt
      saturation_upper: 186  # Calibrated from casa.txt
      value_lower: 153  # Calibrated from casa.txt
      value_upper: 255  # Calibrated from casa.txt

    quadrado:
      hue_lower: 106  # Calibrated from quadrado.txt
      hue_upper: 146  # Calibrated from quadrado.txt
      saturation_lower: 0  # Calibrated from quadrado.txt
      saturation_upper: 169  # Calibrated from quadrado.txt
      value_lower: 39  # Calibrated from quadrado.txt
      value_upper: 164  # Calibrated from quadrado.txt

    quadrado2:
      hue_lower: 10
      hue_upper: 30
      saturation_lower: 90  # 100 - 10% = 90
      saturation_upper: 255  # 255 + 10% = 280.5, capped at 255
      value_lower: 27  # 30 - 10% = 27
      value_upper: 132  # 120 + 10% = 132

telemetry_recorder:
  ros__parameters:
    recording:
      enable: false
      max_duration_minutes: 10
      max_file_size_mb: 1000
      include_images: false
      recording_formats: ["rosbag"]
      output_directory: "~/frtl_2025_ws/flight_logs/onboard"
      autosave_time: 300.0  # Auto-save every 5 minutes