# Onboard computer

oak_rgb_publisher:
  ros__parameters:
    publish_raw: true
    publish_compressed: false
    width: 800
    height: 800
    fps: 10
    auto_exposure_compensation: 1

fase3_color_detector:
  ros__parameters:
    image_topic: '/vertical_camera'
    area_minima_bases: 2000  # Increased to reduce false positives
    
    # Debug mode parameters - similar to CBR base_detector
    full_debug_mode: false  # Publishes full-quality annotated images for debugging
    light_debug_mode: true  # Publishes compressed images at 3Hz for telemetry
    light_debug_topic: '/telemetry/camera_debug/compressed'
    light_debug_size: 400  # Resize debug images to 400x400 for bandwidth
    light_debug_quality: 75  # JPEG compression quality (75% for good quality/size balance)
    
    circulo:
      hue_lower: 109
      hue_upper: 124
      saturation_lower: 37
      saturation_upper: 153
      value_lower: 139
      value_upper: 234

    triangulo:
      hue_lower: 116
      hue_upper: 131
      saturation_lower: 69
      saturation_upper: 99
      value_lower: 85
      value_upper: 115

    hexagono:
      hue_lower: 0
      hue_upper: 9
      saturation_lower: 66
      saturation_upper: 201
      value_lower: 133
      value_upper: 255

    hexagono2: # Para wrap-around do vermelho
      hue_lower: 170
      hue_upper: 180
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 120
      value_upper: 255

    pentagono:
      hue_lower: 0
      hue_upper: 13
      saturation_lower: 23
      saturation_upper: 152
      value_lower: 116
      value_upper: 158

    estrela:
      hue_lower: 40
      hue_upper: 80
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 50
      value_upper: 255

    cruz:
      hue_lower: 143
      hue_upper: 158
      saturation_lower: 90
      saturation_upper: 136
      value_lower: 121
      value_upper: 151

    casa:
      hue_lower: 0
      hue_upper: 14
      saturation_lower: 108
      saturation_upper: 174
      value_lower: 159
      value_upper: 193

    quadrado:
      hue_lower: 0
      hue_upper: 151
      saturation_lower: 22
      saturation_upper: 68
      value_lower: 75
      value_upper: 114

    quadrado2:
      hue_lower: 10
      hue_upper: 30
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 30
      value_upper: 120

telemetry_recorder:
  ros__parameters:
    recording:
      enable: false
      max_duration_minutes: 10
      max_file_size_mb: 1000
      include_images: false
      recording_formats: ["rosbag"]
      output_directory: "~/frtl_2025_ws/flight_logs/onboard"
      autosave_time: 300.0  # Auto-save every 5 minutes