# Simulation configuration - development and testing
# Inherits from common.yaml with simulation-specific overrides

base_detector:
  ros__parameters:
    # Image subscription and Detector publisher topics
    image_topic: '/vertical_camera'
    detection_topic: '/vertical_camera/classification'

    # Full debug mode (enabled for simulation)
    full_debug_mode: true
    mask_debug_topic: '/base_detector/mask_debug'
    bbox_debug_topic: '/base_detector/bbox_debug'

    # Light debug mode
    light_debug_mode: true
    light_debug_topic: '/telemetry/camera_debug/compressed'
    light_debug_size: 400  # Resize debug images to 400x400 for bandwidth
    light_debug_quality: 85  # Higher quality for simulation (more bandwidth available)

    # Morphological operations (color-specific)
    yellow_morph_kernel_size: 3
    yellow_morph_iterations: 2
    blue_morph_kernel_size: 5
    blue_morph_iterations: 3
    
    # HSV color ranges (same as base_detector)
    blue_lower_h: 100
    blue_lower_s: 80
    blue_lower_v: 40
    blue_upper_h: 130
    blue_upper_s: 255
    blue_upper_v: 255
    
    yellow_lower_h: 20
    yellow_lower_s: 120
    yellow_lower_v: 70
    yellow_upper_h: 30
    yellow_upper_s: 255
    yellow_upper_v: 255
    
    # Detection constraints for combined regions
    combined_min_area: 1000
    combined_max_area: 500000
    combined_aspect_ratio_min: 0.5
    combined_aspect_ratio_max: 2.0
    
    # Dilation parameters for combining adjacent color regions
    combination_kernel_size: 15
    combination_iterations: 1


telemetry_recorder:
  ros__parameters:
    recording:
      enable: true
      max_duration_minutes: 10
      max_file_size_mb: 1000
      include_images: false
      recording_formats: ["rosbag"]
      output_directory: "~/frtl_2025_ws/flight_logs/simulation"
      autosave_time: 180.0  # Auto-save every 3 minutes


telemetry_dashboard:
  ros__parameters:
    network:
      ping_target: "192.168.0.152"  # Network monitoring target
      ground_station_ip: "192.168.0.100"
    topics:
      position: "/telemetry/position"
      drone_status: "/telemetry/drone_status"
      system_health: "/telemetry/system_health" 
      logs: "/telemetry/logs"


telemetry_handler:
  ros__parameters:
    visualization:
      known_base_radius: 1.5    