# Onboard computer

oak_rgb_publisher:
  ros__parameters:
    publish_raw: true
    publish_compressed: false
    width: 800
    height: 800
    fps: 10
    auto_exposure_compensation: 1


# base_detector:
#   ros__parameters:
#     # Image subscription and Detector publisher topics
#     image_topic: '/vertical_camera'
#     detection_topic: '/vertical_camera/classification'

#     # Full debug mode
#     full_debug_mode: false

#     # Light debug mode
#     light_debug_mode: true
#     light_debug_topic: '/telemetry/camera_debug/compressed'
#     light_debug_size: 400  # Resize debug images to 400x400 for bandwidth
#     light_debug_quality: 75  # JPEG compression quality (75% for good quality/size balance)
    
#     # Morphological operations (color-specific)
#     yellow_morph_kernel_size: 15
#     yellow_morph_iterations: 6
#     blue_morph_kernel_size: 15
#     blue_morph_iterations: 6
    
#     # HSV color ranges (same as base_detector)
#     blue_lower_h: 90
#     blue_lower_s: 70
#     blue_lower_v: 40
#     blue_upper_h: 135
#     blue_upper_s: 255
#     blue_upper_v: 255
    
#     yellow_lower_h: 15
#     yellow_lower_s: 70
#     yellow_lower_v: 40
#     yellow_upper_h: 35
#     yellow_upper_s: 255
#     yellow_upper_v: 255
    
#     # Detection constraints for combined regions
#     combined_min_area: 0.03
#     combined_max_area: 1.1
#     combined_aspect_ratio_min: 0.75
#     combined_aspect_ratio_max: 1.3
    
#     # Dilation parameters for combining adjacent color regions
#     combination_kernel_size: 15
#     combination_iterations: 1

fase3_color_detector:
  ros__parameters:
    image_topic: '/vertical_camera'
    area_minima_bases: 300  # Increased to reduce false positives
    
    # Debug mode parameters - similar to CBR base_detector
    full_debug_mode: false  # Publishes full-quality annotated images for debugging
    light_debug_mode: true  # Publishes compressed images at 3Hz for telemetry
    light_debug_topic: '/telemetry/camera_debug/compressed'
    light_debug_size: 400  # Resize debug images to 400x400 for bandwidth
    light_debug_quality: 75  # JPEG compression quality (75% for good quality/size balance)
    
    circulo:
      hue_lower: 100
      hue_upper: 130
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 120
      value_upper: 255

    triangulo:
      hue_lower: 100
      hue_upper: 130
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 50
      value_upper: 120

    hexagono:
      hue_lower: 0
      hue_upper: 10
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 120
      value_upper: 255

    hexagono2: # Para wrap-around do vermelho
      hue_lower: 170
      hue_upper: 180
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 120
      value_upper: 255

    pentagono:
      hue_lower: 0
      hue_upper: 10
      saturation_lower: 200
      saturation_upper: 255
      value_lower: 60
      value_upper: 120

    estrela:
      hue_lower: 40
      hue_upper: 80
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 50
      value_upper: 255

    cruz:
      hue_lower: 140
      hue_upper: 170
      saturation_lower: 80
      saturation_upper: 255
      value_lower: 80
      value_upper: 255

    casa:
      hue_lower: 10
      hue_upper: 25
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 100
      value_upper: 255

    quadrado:
      hue_lower: 0
      hue_upper: 180
      saturation_lower: 0
      saturation_upper: 255
      value_lower: 0
      value_upper: 50

    quadrado2:
      hue_lower: 10
      hue_upper: 30
      saturation_lower: 100
      saturation_upper: 255
      value_lower: 30
      value_upper: 120

telemetry_recorder:
  ros__parameters:
    recording:
      enable: false
      max_duration_minutes: 10
      max_file_size_mb: 1000
      include_images: false
      recording_formats: ["rosbag"]
      output_directory: "~/frtl_2025_ws/flight_logs/onboard"
      autosave_time: 300.0  # Auto-save every 5 minutes